#!/usr/bin/env bash

# This script prepares the users filesystem

GRN="\e[32m"
CLR="\e[0m"


TOOLCHAIN=`node -p "require('nodeos-cross-toolchain')"`
BAREBONES=`node -p "require('nodeos-barebones')"`
INITRAMFS=`node -p "require('nodeos-initramfs')"`

NODE_DIR=`node -p "require('nodeos-nodejs')"`

source $TOOLCHAIN/scripts/adjustEnvVars.sh &&
source scripts/utils.sh                    || exit $?

PATH=$TOOLCHAIN/bin:$PATH


# Clean object dir and return the input error
function err(){
  rmStep $STEP_DIR
  exit $1
}


#
# Define steps paths
#

OBJ_ROOT=$OBJECTS/root
OBJ_NODEOS=$OBJECTS/nodeos
OUT_DIR=`pwd`/out/$CPU


#
# root home
#

STEP_DIR=$OBJ_ROOT

if [[ ! -d $STEP_DIR ]]; then
  echo -e "${WHT}Generating root user folder${CLR}"

  # Force re-creation of usersfs
  rm -rf $OUT_DIR || exit 14

  (
    mkdir -p $STEP_DIR || exit 10

    #
    # Install system dependencies
    #

    PACKAGES=`node -p "require('./package.json').nodeosDependenciesRoot.join(' ')"`
    eval "$NPMi" -g $PACKAGES || exit 11


    #
    # Services to be started at boot
    #

    mkdir -p $STEP_DIR/etc                 &&
    cp forever-starter.json $STEP_DIR/etc/ || exit 12


    #
    # Init file for the user
    #

    ln -sf bin/forever-starter $STEP_DIR/init || exit 13
  ) || err $?

  echo -e "${GRN}Successfully generated root user folder${CLR}"
fi


#
# nodeos home
#

STEP_DIR=$OBJ_NODEOS

if [[ ! -d $STEP_DIR ]]; then
  echo -e "${WHT}Generating nodeos user folder${CLR}"

  # Force re-creation of usersfs
  rm -rf $OUT_DIR || exit 25

  (
    mkdir -p $STEP_DIR || exit 20

    #
    # Install user dependencies
    #

    PACKAGES=`node -p "require('./package.json').nodeosDependenciesNodeos.join(' ')"`
    eval "$NPMi" -g $PACKAGES || exit 21


    #
    # Copy nodeos user login info
    #

    mkdir -p $STEP_DIR/etc        &&
    cp logon.json  $STEP_DIR/etc/ || exit 22


    #
    # Dummy init file for the user
    #

    cp init.js $STEP_DIR/init || exit 23


    #
    # blessed-contrib examples
    #

    BLESSED_URL=https://github.com/yaronn/blessed-contrib/archive/master.tar.gz
    SRC_DIR=$STEP_DIR/blessed-contrib

    mkdir -p $SRC_DIR                                                 &&
    curl -L $BLESSED_URL | tar xzf - -C $SRC_DIR --strip-components=1 &&
    (
      cd $SRC_DIR

      eval "$NPMi" || exit 24
    ) || exit $?


    # #
    # # node-canvas examples
    # #
    #
    # CANVAS_URL=https://github.com/NodeOS/node-canvas/archive/master.tar.gz
    # SRC_DIR=$OBJ_DIR/node-canvas
    #
    # mkdir -p $SRC_DIR                                                &&
    # curl -L $CANVAS_URL | tar xzf - -C $SRC_DIR --strip-components=1 &&
    # (
    #   cd $SRC_DIR
    #
    #   eval "$NPMi" --has_cairo=false --has_X11=false || exit 25
    # ) || exit $?
  ) || err $?

  echo -e "${GRN}Successfully generated nodeos user folder${CLR}"
fi


#
# Wrap the system up and pack it
#

STEP_DIR=$OUT_DIR

if [[ ! -f $STEP_DIR ]]; then
  mkdir -p `dirname $STEP_DIR`

  case $PLATFORM in
    docker|vagga)
      cp $BAREBONES/out/latest $STEP_DIR/barebones.tar || err 30
      cp $INITRAMFS/out/latest $STEP_DIR/initramfs.tar || err 31

      chmod -R go= "$OBJECTS" || err 32

      ln -sf ../build/$CPU out/latest || err 33
    ;;

    pc_* | raspberry_*)
      DISK_SIZE=192  # Size in MB

      genext2fs -b $((DISK_SIZE*1024)) \
          --root $OBJECTS              \
          --block-size          1024   \
          --bytes-per-inode     4096   \
          --reserved-percentage    0   \
          --creator-os linux           \
          --allow-holes                \
          --squash $STEP_DIR           || err 40

      # Set filesystem features and users files permissions
      tune2fs   $STEP_DIR -O has_journal,filetype > /dev/null || err 41
      e2fsck -y $STEP_DIR                         > /dev/null
      if [ $? -gt 2 ]; then
        err 42
      fi
      debugfs.chown $STEP_DIR nodeos 1 || err 43

      # Mark the newly created filesystem image as the latest one
      ln -sf $CPU out/latest || err 44
    ;;

    *)
      echo -e "${RED}Unknown platform '$PLATFORM'${CLR}"
      err 50
    ;;
  esac
fi


echo -e "${GRN}Successfully built Layer-3 image 'usersfs'${CLR}"
